FROM mcr.microsoft.com/devcontainers/base:bookworm
ENV DEBIAN_FRONTEND=noninteractive
#RUN apt update && apt install -y bash-completion libpci-dev libegl-dev libegl1-mesa-dev && apt clean && rm -rf /var/lib/apt/lists/*